Handle file-like objects with integer name attribute
smartfile/python-libarchive pull request #12
Opened 2020-03-04 17:47 UTC by aaron-sierra

While working with streaming output from `rpmcpio` via `subprocess.Popen.stdout` and the high-level libarchive interface, I found that I couldn't get past an exception from `guess_format()`:
```
File "/path/to/venv/lib/python3.6/site-packages/libarchive/__init__.py", line 419, in __init__
    filter = guess_format(self.filename)[1]
  File "/path/to/venv/lib/python3.6/site-packages/libarchive/__init__.py", line 120, in guess_format
    filename, ext = os.path.splitext(filename)
  File "/usr/lib/python3.6/posixpath.py", line 122, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not int
```

I tried setting `Archive(p.stdout, format='cpio')`, but since `filter` was `None`, I couldn't get past `guess_format()`.

I found that when `io.BufferedReader` (and others) are init-ed based on a file descriptor, their name attribute will be an integer. These objects can be handled by trapping `TypeError` in `guess_format()` and setting sane values (empty strings).

I'd considered adding an explicit `'none'` filter to the `FILTERS` dictionary to differentiate it from an undefined keyword argument, but I obviously passed on that.

2020-03-10 13:57 UTC, cabarnes requested changes
Can you add a test for this? Otherwise, I think this is a reasonable approach to handle that issue.

2020-03-10 18:05 UTC, aaron-sierra commented
> Can you add a test for this?

Sure thing.

2020-03-11 03:05 UTC, aaron-sierra commented
There was quite a bit more work than probably either of us anticipated. I've changed my original fix (last commit) to more cleanly support Python 2 and 3.

2020-03-11 17:28 UTC, cabarnes commented
@aaron-sierra Thanks a lot for all these improvements. Everything looks good. You identified that the zipfile isn't cleaned up in the tests. If you'd like to add the cleanup as well, I'd be fine if you included it in this. Otherwise, I will go ahead and merge since it will be behaving the same way as before.

2020-03-11 20:04 UTC, aaron-sierra commented
> You identified that the zipfile isn't cleaned up in the tests. If you'd like to add the cleanup as well, I'd be fine if you included it in this. Otherwise, I will go ahead and merge since it will be behaving the same way as before.

I'd rather leave that to future work, since there appears to be some refactoring needed to let cleanup run within each test case's `tearDown`. That stems from `tempfile.mkdtemp()` not just giving a name for tests to share, but an initial directory, too. Maybe you'll want a new `unittest.TestCase` subclass with `setUp`/`tearDown` that all of the other tests build off of? :man_shrugging:

2020-03-11 20:13 UTC, cabarnes approved these changes
Thanks! Looks good

2020-03-11 20:13 UTC, merged