readpath: fix getting basedir
smartfile/python-libarchive pull request #13
Opened 2020-07-02 11:52 UTC by kmichonski

I assume that was the originally intended behaviour.
This way it creates directory to which archive's entry will be extracted.
Otherwise it will just create empty files that later remain unused.

It's pretty self explanatory but here's an example:
```python
❯ ls
archive.cpio  output
❯ cpio -it < archive.cpio 
postinstall.sh
sw-description
uImage-kernel-5.1.7-dtb-imx6q-dss11e.bin
8428 blocks
❯ python3.8
Python 3.8.3 (default, May 15 2020, 00:00:00) 
[GCC 10.1.1 20200507 (Red Hat 10.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os, libarchive
>>> with libarchive.Archive("archive.cpio", "r", format="cpio") as archive:
...     for entry in archive:
...             archive.readpath(os.path.join("./output/", entry.pathname))
... 
0
0
0
>>> 
❯ ls # as visible here: additional directory was created for each entry,
# extraction is fine but superfluous directories are there
archive.cpio  postinstall.sh  uImage-kernel-5.1.7-dtb-imx6q-dss11e.bin
output        sw-description
```

2020-07-07 18:05 UTC, cabarnes requested changes
If you would be willing to add tests to cover this, that would be appreciated

2020-07-07 18:05 UTC, cabarnes commented on libarchive/__init__.py
>              if not os.path.exists(basedir):
I believe that you are correct with the above change. However, this will now fail if just the filename is passed. I believe this line will also need to check `if basedir and not os.path.exists(basedir)`

2020-07-23 10:06 UTC, kmichonski commented on libarchive/__init__.py
>              if not os.path.exists(basedir):
Pushed suggested change

2020-08-31 20:08 UTC, cabarnes commented
@kmichonski It seems that the merge with `master` has overridden your change of `basename` -> `dirname`. I'm not sure this is fixing the issue that you had before

2022-03-11 10:45 UTC, closed without merging